# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, acidState, aeson, ansiWlPprint, async, commandQq
, dataDefaultClass, directoryLayout, exceptions, filepath, free
, hspec, hspecExpectationsLens, HStringTemplate, lens, meep, mtl
, optparseApplicative_0_10_0, pointed, reflection, safecopy, semigroups
, stm, tagged, taggedTransformer, temporary, terminalSize, text
, transformers, void
}:

cabal.mkDerivation (self: {
  pname = "biegunka";
  version = "0.2";
  src = ../../git/biegunka/.;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    acidState aeson ansiWlPprint async commandQq dataDefaultClass
    directoryLayout exceptions filepath free hspec HStringTemplate lens
    meep mtl optparseApplicative_0_10_0 pointed reflection safecopy semigroups
    stm tagged taggedTransformer terminalSize text transformers void
  ];
  testDepends = [
    dataDefaultClass directoryLayout filepath free hspec
    hspecExpectationsLens lens optparseApplicative_0_10_0 semigroups temporary
    text transformers
  ];
  meta = {
    homepage = "http://biegunka.budueba.com/";
    description = "Configuration development";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
  doCheck = false; # https://github.com/biegunka/biegunka/issues/62
})
