language: haskell

ghc:
 - 7.6
 - 7.8

before_install:
 - sudo apt-get update
 - sudo apt-get install c2hs
 - cabal install cabalg

install:
 - cabalg git://github.com/acid-state/acid-state.git
 - cabalg git://github.com/biegunka/biegunka.git --branch=develop
 - cabal install biegunka/dotfiles.cabal

script: true
