language: haskell

ghc:
 - 7.6
 - 7.8

install:
    - cabal install cabalg
    - cabalg https://github.com/supki/temporary https://github.com/acid-state/acid-state https://github.com/biegunka/biegunka@develop -- biegunka/dotfiles.cabal

script: true

