language: haskell

ghc:
    - 7.8

env:
    matrix:
        - ENV=qumsrc
        - ENV=s10
        - ENV=w540

before_install:
    - |
      bash <(curl -sS https://nixos.org/nix/install)
      source $HOME/.nix-profile/etc/profile.d/nix.sh
      nix-channel --update

install:
    - nix-shell -p '(haskellngPackages.callPackage ./default.nix { })' --command 'dotfiles --${ENV} --changes'

script: true
