# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, bencoding, binary, dataDefault, filepath, hspec, HUnit
, lens, QuickCheck, quickcheckInstances
}:

cabal.mkDerivation (self: {
  pname = "hstorrent";
  version = "0.1.0.0";
  src = (builtins.getEnv "HOME") + "/git/hstorrent";
  buildDepends = [
    bencoding binary dataDefault lens QuickCheck quickcheckInstances
  ];
  testDepends = [
    bencoding binary dataDefault filepath hspec HUnit lens QuickCheck
    quickcheckInstances
  ];
  meta = {
    homepage = "https://github.com/hstorrent/hstorrent";
    description = "BitTorrent library in Haskell";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
