source ${HOME}/prexinit

# run trayer
trayer --edge bottom --align left --transparent true --widthtype pixel --width 100 --heighttype pixel --height 10 --tint 0x080808 --alpha 0 --SetDockType true &

# run kbdd daemon
/usr/bin/kbdd &

# run xscreensaver daemon
xscreensaver -no-splash &

# process urxvt settings
xrdb ~/.Xdefaults
xrdb -override ~/.Xresources.scratchpad
xrdb -override ~/.Xresources.shiva
xrdb -override ~/.Xresources.large

# run unclutter to hide cursor
unclutter &

# run ssh-agent
eval `ssh-agent`
ssh-add ~/.ssh/id_rsa

# enable wallpaper
feh --bg-scale ~/img/w/w.jpg

# compositing
xcompmgr -c &

# run xmonad
exec ck-launch-session dbus-launch xmonad
