source ${HOME}/.prexinit

# run trayer
trayer --edge top --align left --transparent true --widthtype pixel --width 120 --heighttype pixel --height 10 --tint 0x080808 --alpha 0 --SetDockType true &

# run kbdd daemon
/usr/bin/kbdd &

# process urxvt settings
xrdb ~/.Xresources
xrdb -override ~/.Xresources.scratchpad
xrdb -override ~/.Xresources.shiva
xrdb -override ~/.Xresources.large

# run unclutter to hide cursor
unclutter &

# run ssh-agent
eval `ssh-agent`
ssh-add ~/.ssh/id_rsa
ssh-add ~/.ssh/id_dsa

# run xmonad
exec ck-launch-session dbus-launch xmonad
