resolver: lts-12.04
packages:
  - '.'
allow-newer: true
extra-deps:
  - blaze-html-0.9.1.1
  - blaze-markup-0.8.2.1
  - conduit-1.2.13.1
  - conduit-extra-1.2.3.2
  - hspec-expectations-lens-0.4.0
  - html-conduit-1.2.1.2
  - liblastfm-0.7.0
  - resourcet-1.1.11
  - streaming-commons-0.1.17
  - xml-conduit-1.7.1.2
  - xml-html-conduit-lens-0.3.2.1
  - github: supki/scrobblers
    commit: ff8f0ab308f881139ef486fe7933b9dc160752b2
ghc-options:
  "$locals": -fhide-source-paths
