"=====================================
" GENERAL SETTINGS
"=====================================
    " drop vi shit
    set nocompatible

    " do not making backup before editing file
    set nobackup

    " do not using swapfile
    set noswapfile

    " number of lines that are remembered
    set history=100

    " automatically reload file, when it's changed outside of Vim
    set autoread

    " Maximum number of changes that can be undone
    set undolevels=100

    "  list of character encodings considered when starting to edit an existing file
    set fileencodings=utf-8

    call pathogen#infect()
    filetype plugin indent on

    " share clipboard among instances
    set clipboard=unnamed

    " prevents some security exploits having to do with modelines in files
    set modelines=0

    set ttyfast

    " enable neocomplcache
    let g:neocomplcache_enable_at_startup = 1
    let g:neocomplcache_force_overwrite_completefunc = 1

"=====================================
" FUNCTIONS
"=====================================
    " chmod +х to scripts
    function ModeChange()
        if getline(1) =~ '^#!'
            silent !chmod a+x <afile>
        endif
    endfunction


"=====================================
" PLUGINS
"=====================================
 if has('vim_starting')
   set runtimepath+=~/.vim/bundle/neobundle.vim/
 endif

 call neobundle#rc(expand('~/.vim/bundle/'))

 NeoBundleFetch 'Shougo/neobundle.vim'

 NeoBundle 'Shougo/vimproc', {'build': {'linux': 'make -f make_unix.mak' } }

 NeoBundle "Shougo/neocomplcache"
 NeoBundle "Shougo/unite.vim"
 NeoBundle "airblade/vim-gitgutter"
 NeoBundle "dahu/Insertlessly"
 NeoBundle "godlygeek/tabular"
 NeoBundle "scrooloose/syntastic"
 NeoBundle "spolu/dwm.vim"
 NeoBundle "supki/vim-perds"
 NeoBundle "tpope/vim-commentary"
 NeoBundle "tpope/vim-surround"
 NeoBundle "ujihisa/neco-ghc"
 NeoBundle "jvoorhis/coq.vim"
 NeoBundle "trefis/coquille"
 NeoBundle "def-lkb/vimbufsync"
 NeoBundle "merlinrebrovic/focus.vim"
 NeoBundle "vim-scripts/YankRing.vim"
 NeoBundle "derekwyatt/vim-sbt"
 NeoBundle "elzr/vim-json"
 NeoBundle "eagletmt/ghcmod-vim"
 NeoBundle "bitc/vim-hdevtools"
 NeoBundle "git@github.com:kongo2002/fsharp-vim.git"

 NeoBundleCheck

"=====================================
" APPEARANCE SETTINGS
"=====================================
    syntax on

    " Syntax coloring lines that are too long just slows down the world
    set synmaxcol=2048

    set background=dark

    " Show the current mode
    set showmode

    set statusline=#%n\ %f\ %y\ %{'['.(&fenc!=''?&fenc:&enc).':'.']'}\ %m\ %r\ %=%l,%c/%L

    " Show the current command in the lower right corner
    set showcmd
    " Show status line for all files
    set laststatus=2
    " Show matching brackets
    set showmatch
    " Do case insensitive matching
    set ignorecase
    " Ignore case when the pattern contains lowercase letters only.
    set smartcase

    colorscheme neverland-darker

    set cursorline
    set cursorcolumn
    hi CursorLine ctermbg=235
    hi CursorColumn ctermbg=235

    set relativenumber

    " enable autocomplete
    set wildmenu
    set wildmode=list:longest,full

    " make vim message not to annoy
    set shortmess=aoOIT

    " always report about changed lines
    set report=0

    " Don't update the display while executing macros
    set lazyredraw

    " Nice-looking vertical separator
    set fillchars=vert:│

    " Cyrillic mapping
    set langmap=ёйцукенгшщзхъфывапролджэячсмитьбюЁЙЦУКЕHГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ;`qwertyuiop[]asdfghjkl\\;'zxcvbnm\\,.~QWERTYUIOP{}ASDFGHJKL:\\"ZXCVBNM<>

"=====================================
" MISC SETTINGS
"=====================================
    set tabstop=4
    set shiftwidth=4
    set softtabstop=4
    set expandtab
    set autoindent

    " matched string is highlighted.
    set incsearch

    " lines to scroll when cursor leaves screen
    set scrolljump=10
    " lines before screen edge to scroll
    set scrolloff=1000

    " Don't searches wrap around the end of the file
    set nowrapscan
    " enable wrap
    set wrap
    " wrap backspace, space, h, l, <-, ->, [ and ] keys
    set whichwrap=b,s,<,>,[,],l,h
    " set word-wrap, not symbol-wrap
    set linebreak

    set colorcolumn=80

    " I should do nothing, REMOVE ME
    if $TMUX == ''
        set clipboard+=unnamed
    endif

    " some Haskell properties
    hi hsNiceOperator ctermfg=none ctermbg=black
    autocmd FileType haskell setlocal expandtab shiftwidth=2 softtabstop=2
    " configure browser for haskell_doc.vim
    let g:haddock_browser = "firefox-bin"
    " syntax rules
    let hs_highlight_delimiters = 1
    let hs_highlight_boolean = 1
    let hs_highlight_debug = 1
    let hs_highlight_more_types = 1
    let hs_highlight_types = 1
    " ghc-mod customs
    let g:ghcmod_ghc_options = ['-Wall','-fno-warn-missing-signatures', '-fno-warn-unused-do-bind', '-fno-warn-type-defaults']
    autocmd bufwritepost *.hs :GhcModCheck
    " for vim-commentary
    autocmd FileType haskell set commentstring=--\ %s

    let g:syntastic_mode_map = { 'mode': 'active', 'active_filetypes': [], 'passive_filetypes': ['haskell','tex','java']}
    let g:syntastic_python_checkers=['flake8']
    let g:syntastic_python_checker_args='--ignore=E501'

    " Use ruby syntax for capfiles
    autocmd Bufenter *.[cC]apfile,[cC]apfile setfiletype ruby
    autocmd FileType ruby setlocal expandtab shiftwidth=2 softtabstop=2

    autocmd Bufenter *.md setfiletype markdown

    " Use haskell syntax for biegunkofiles
    autocmd Bufenter *.biegunka setfiletype haskell

    " set XML style
    " let g:xml_syntax_folding=1
    autocmd FileType xml setlocal expandtab shiftwidth=2 softtabstop=2 foldmethod=syntax

    autocmd FileType eruby,javascript,sh setlocal expandtab shiftwidth=2 softtabstop=2

    " ingore whitespaces (vimdiff)
    set diffopt+=iwhite " ignore whitespaces

    " highlight trailing spaces
    set list!
    set listchars=tab:»»,trail:∘
    " disable matches in help buffers
    autocmd BufEnter,FileType help call clearmatches()

    " Automatically chmod +x
    autocmd BufWritePost * call ModeChange()

    " preserve undo actions even after file has closed
    set undolevels=1000
    set undofile

    " vim-latex settings
    set grepprg=grep\ -nH\ $*
    let g:tex_flavor='latex'

    " save after losing focus
    autocmd FocusLost * :wa

    " clear signcolumn for Syntastic and GitGutter
    highlight clear SignColumn
    highlight GitGutterAdd ctermfg=000 ctermbg=003
    highlight GitGutterChange ctermfg=000 ctermbg=022
    highlight GitGutterDelete ctermfg=000 ctermbg=010
    highlight GitGutterChangeDelete ctermfg=000 ctermbg=010

    if &term =~ '^screen'
        " tmux will send xterm-style keys when xterm-keys is on
        execute "set <xUp>=\e[1;*A"
        execute "set <xDown>=\e[1;*B"
        execute "set <xRight>=\e[1;*C"
        execute "set <xLeft>=\e[1;*D"
    endif

    " yank-ring settings
    let g:yankring_replace_n_pkey = '<Leader>p'
    let g:yankring_replace_n_nkey = '<Leader>n'

"=====================================
" GVIM SETTINGS
"=====================================
    set guifont=Terminus\ 8
    set guioptions=ac

"=====================================
" KEY MAPPING SETTINGS
"=====================================
    let mapleader = ","

    " remove search highlighting
    nmap <Leader>nh :nohlsearch<CR>

    " set paste mode
    set pastetoggle=<F3>

    noremap k gk
    noremap j gj

    " annoying shift and caps
    cnoremap W w
    cnoremap ц w

    noremap <Leader>u :Unite file buffer<CR>

    " save as root with w!!
    cmap w!! w !sudo tee % > /dev/null

    " Edit the vimrc file
    nmap <silent> <Leader>sv :so $MYVIMRC<CR>

    " Close current buffer
    nmap <Leader>d :bd<CR>

    " Close all buffers except current
    nmap <Leader>a :BufOnly<CR>

    " disable arrow keys in insert and normal modes
    inoremap <up> <nop>
    inoremap <down> <nop>
    inoremap <left> <nop>
    inoremap <right> <nop>
    nnoremap <up> <nop>
    nnoremap <down> <nop>
    nnoremap <left> <nop>
    nnoremap <right> <nop>

    " Haskell maps
    autocmd FileType haskell nnoremap <buffer> <F3> :GhcModLint<CR>
    autocmd FileType haskell nnoremap <buffer> <F4> :GhcModCheck<CR>
    autocmd FileType haskell nnoremap <buffer> <F5> :HdevtoolsType<CR>
    autocmd FileType haskell nnoremap <buffer> <F6> :HdevtoolsClear<CR>
    autocmd FileType haskell nnoremap <Leader>sh :%!stylish-haskell<CR>

    autocmd FileType coq call coquille#CoqideMapping()

    " git splitspace
    nmap <Leader>s :%!git stripspace<CR>

    nnoremap <F6> :%s/<c-r><c-w>//gc<left><left><left>
