#!/bin/zsh

function _contains() {
    ${1[(r)$2]}
}

function _with_spaces() {
    if [ -n "$1" ]; then
        echo " $1 "
    fi
}

allowed_functions=(get_tmux_pwd git_branch git_diff_insertions git_diff_deletions)


function get_tmux_pwd() {
    tmux show-environment $(tmux display -p "TMUXPWD_#D" | sed 's/%//') | sed 's/.*=//'
}

function gitable() {
    git -C ${~$(get_tmux_pwd)} rev-parse --git-dir > /dev/null 2>&1
}

function git_branch() {
    if gitable; then
        echo "$(git -C ${~$(get_tmux_pwd)} rev-parse --abbrev-ref HEAD)"
    fi
}

function git_diff_insertions() {
    if gitable; then
        _with_spaces $(git -C ${~$(get_tmux_pwd)} diff --stat | grep -o -P "(?<= )[0-9]+(?= insertion)")
    fi
}

function git_diff_deletions() {
    if gitable; then
        _with_spaces $(git -C ${~$(get_tmux_pwd)} diff --stat | grep -o -P "(?<= )[0-9]+(?= deletion)")
    fi
}

if _contains $allowed_functions $1; then
    eval $1
fi

