# number of lines kept in history
export HISTSIZE=1000
# number of lines saved in the history after logout
export SAVEHIST=1000
# location of history
export HISTFILE=~/.zhistory
# append command to history file once executed
setopt inc_append_history
# autocompletion of command line switches for aliases
setopt completealiases

export TERM='screen-256color'
export COLORTERM='screen--256color'
export EDITOR=vim
export SSL_CERT_FILE='' # deleting nix considered harmful
typeset -U path
path=(/usr/local/tranquil/bin /usr/local/opt/coreutils/libexec/gnubin/ ~/bin ~/.local/bin/ ~/.cabal/bin/ /usr/local/bin/ $path)
