autoload -U compinit promptinit colors

# completion settings
fpath=(~/git/zsh-completions/src $fpath)
compinit
zstyle ':completion::complete:*' use-cache 1

# vi mode
bindkey -v
export KEYTIMEOUT=1

# prompt settings
promptinit
colors
export PROMPT="%(?,%F{2},%F{1})>> %f"

alias ssh='TERM=xterm-color ssh'
alias ihach='iconv -cf inis-cyrillic'
alias ls='ls --color=auto'

# external monitor helper
declare MAINDISPLAY=LVDS1
function setdisplay() {
    local -r NEWDISPLAY=${2:-DP2}
    case $1 in
            on)     xrandr --output $NEWDISPLAY --same-as $MAINDISPLAY --auto ;;
            off)    xrandr --output $NEWDISPLAY --off ;;
            *)      echo "Wrong argument"; return 1 ;;
    esac
}

function flac2mp3() {
    in=${1}
    out=${in:r}.mp3
    flac -d ${in} -c | lame - ${out} -b 320
}

# ruby stuff
unset RUBYOPT

# nixos stuff
if [[ -n "$(uname -a | grep -i -o "nixos")" ]]; then
    nixpkgs_head=/home/yep/git/nixpkgs/
    [[ -z "$(grep -o ${nixpkgs_head} <<< ${NIX_PATH})" ]] && export NIX_PATH=nixpkgs=${nixpkgs_head}:${NIX_PATH}
fi

bindkey '^R' history-incremental-search-backward
source ~/.zshenv
