autoload -U compinit promptinit colors

# completion settings
compinit
zstyle ':completion::complete:*' use-cache 1

# prompt settings
promptinit
colors
precmd() { print -rP ""; print -rP "$fg[yellow][ $fg[green]%~ $fg[yellow]]" }
export PROMPT="$> "

# number of lines kept in history
export HISTSIZE=1000
# number of lines saved in the history after logout
export SAVEHIST=1000
# location of history
export HISTFILE=~/.zhistory
# append command to history file once executed
setopt inc_append_history
# autocompletion of command line switches for aliases
setopt completealiases

export TERM='rxvt-256color'
export COLORTERM='rxvt-unicode-256color'
export EDITOR=vim

alias xinit_='cp ~/.xinit_log{,_old} && xinit |& tee ~/.xinit_log'
alias sml='rlwrap sml'
alias ssh='TERM=xterm-color ssh'
alias racket='rlwrap racket'
alias mvn='mvn-2.2'
alias git-home='cd $(git rev-parse --show-toplevel)'
alias ihach='iconv -cf inis-cyrillic'
alias ls='ls --color=auto'
alias idea='~/downloads/idea-IC-129.713/bin/idea.sh'

# external monitor helper
declare MAINDISPLAY=LVDS1
setdisplay() {
    local -r NEWDISPLAY=${2:-DP1}
    source ${HOME}/.prexinit
    case $1 in
            on)     xrandr --output $NEWDISPLAY --same-as $MAINDISPLAY --auto ;;
            off)    xrandr --output $NEWDISPLAY --off ;;
            *)      echo "Wrong argument"; return 1 ;;
    esac
}

# haskell stuff
PATH=${HOME}/bin/:$PATH:${HOME}/.cabal/bin

# ruby stuff
unset RUBYOPT
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

bindkey '^R' history-incremental-search-backward
