autoload -U compinit promptinit colors

# completion settings
fpath=(~/projects/misc/zsh-completions/src $fpath)
compinit
zstyle ':completion::complete:*' use-cache 1

# prompt settings
promptinit
colors
precmd() { print -rP ""; print -rP "$fg[yellow][ $fg[green]%~ $fg[yellow]]" }
export PROMPT="$> "


alias xinit_='cp ~/.xinit_log{,_old} && xinit |& tee ~/.xinit_log'
alias sml='rlwrap sml'
alias ssh='TERM=xterm-color ssh'
alias racket='rlwrap racket'
alias mvn='mvn-2.2'
alias git-home='cd $(git rev-parse --show-toplevel)'
alias ihach='iconv -cf inis-cyrillic'
alias ls='ls --color=auto'
alias idea='~/downloads/idea-IC-129.713/bin/idea.sh'

# external monitor helper
declare MAINDISPLAY=LVDS1
setdisplay() {
    local -r NEWDISPLAY=${2:-DP2}
    case $1 in
            on)     xrandr --output $NEWDISPLAY --same-as $MAINDISPLAY --auto ;;
            off)    xrandr --output $NEWDISPLAY --off ;;
            *)      echo "Wrong argument"; return 1 ;;
    esac
}

flac2mp3() {
    in=${1}
    out=${in:r}.mp3
    flac -d ${in} -c | lame - ${out} -b 320
}

# ruby stuff
unset RUBYOPT

bindkey '^R' history-incremental-search-backward
source ~/.zshenv
